
export const moroccanLocations = [
    { "Ville": "Casablanca", "Région": "Aïn Chock" },
    { "Ville": "Casablanca", "Région": "Aïn Sebaâ" },
    { "Ville": "Casablanca", "Région": "Al Fida" },
    { "Ville": "Casablanca", "Région": "Anfa" },
    { "Ville": "Casablanca", "Région": "Ben M'sik" },
    { "Ville": "Casablanca", "Région": "Essoukhour Assawda (Roches Noires)" },
    { "Ville": "Casablanca", "Région": "Hay Hassani" },
    { "Ville": "Casablanca", "Région": "Hay Mohammadi" },
    { "Ville": "Casablanca", "Région": "Maârif" },
    { "Ville": "Casablanca", "Région": "Mers Sultan" },
    { "Ville": "Casablanca", "Région": "Moulay Rachid" },
    { "Ville": "Casablanca", "Région": "Sbata" },
    { "Ville": "Casablanca", "Région": "Sidi Belyout" },
    { "Ville": "Casablanca", "Région": "Sidi Bernoussi" },
    { "Ville": "Casablanca", "Région": "Sidi Moumen" },
    { "Ville": "Casablanca", "Région": "Sidi Othman" },
    { "Ville": "Casablanca", "Région": "Bouskoura" },
    { "Ville": "Casablanca", "Région": "Dar Bouazza" },
    { "Ville": "Casablanca", "Région": "Oulfa" },
    { "Ville": "Casablanca", "Région": "CIL" },
    { "Ville": "Casablanca", "Région": "Polo" },
    { "Ville": "Casablanca", "Région": "California" },
    { "Ville": "Casablanca", "Région": "Belvédère" },
    { "Ville": "Casablanca", "Région": "Tit Mellil" },
    { "Ville": "Casablanca", "Région": "Lahraouiyine" },
    { "Ville": "Casablanca", "Région": "Mediouna" },
    { "Ville": "Casablanca", "Région": "Nouaceur" },
    { "Ville": "Casablanca", "Région": "Bourgogne" },
    { "Ville": "Casablanca", "Région": "Gauthier" },
    { "Ville": "Casablanca", "Région": "Racine" },
    { "Ville": "Casablanca", "Région": "L'Oasis" },
    { "Ville": "Casablanca", "Région": "Riviera" },
    { "Ville": "Casablanca", "Région": "Beauséjour" },
    { "Ville": "Casablanca", "Région": "Habous" },
    { "Ville": "Casablanca", "Région": "Oulad Haddou" },
    { "Ville": "Casablanca", "Région": "Lissasfa" },
    { "Ville": "Casablanca", "Région": "Sidi Maârouf" },
    { "Ville": "Casablanca", "Région": "Dar Lamane" },
    { "Ville": "Rabat", "Région": "Agdal-Ryad" },
    { "Ville": "Rabat", "Région": "El Youssoufia" },
    { "Ville": "Rabat", "Région": "Hassan" },
    { "Ville": "Rabat", "Région": "Souissi" },
    { "Ville": "Rabat", "Région": "Yacoub El Mansour" },
    { "Ville": "Rabat", "Région": "La Médina" },
    { "Ville": "Rabat", "Région": "L'Océan" },
    { "Ville": "Rabat", "Région": "Hay Riad" },
    { "Ville": "Rabat", "Région": "Akkari" },
    { "Ville": "Rabat", "Région": "Mabrouka" },
    { "Ville": "Rabat", "Région": "Kamra" },
    { "Ville": "Rabat", "Région": "Orangers" },
    { "Ville": "Rabat", "Région": "Diour Jamaa" },
    { "Ville": "Rabat", "Région": "Massira" },
    { "Ville": "Rabat", "Région": "Hay El Fath" },
    { "Ville": "Rabat", "Région": "Bas Agdal" },
    { "Ville": "Rabat", "Région": "Haut Agdal" },
    { "Ville": "Rabat", "Région": "Takadoum" },
    { "Ville": "Rabat", "Région": "Mabella" },
    { "Ville": "Rabat", "Région": "Touargas" },
    { "Ville": "Fès", "Région": "Agdal" },
    { "Ville": "Fès", "Région": "Saiss" },
    { "Ville": "Fès", "Région": "Fès-Médina" },
    { "Ville": "Fès", "Région": "Jnan El Ouard" },
    { "Ville": "Fès", "Région": "El Mariniyine" },
    { "Ville": "Fès", "Région": "Zouagha" },
    { "Ville": "Fès", "Région": "Ville Nouvelle" },
    { "Ville": "Fès", "Région": "Narjiss" },
    { "Ville": "Fès", "Région": "Adarissa" },
    { "Ville": "Fès", "Région": "Oued Fès" },
    { "Ville": "Fès", "Région": "Route d'Imouzzer" },
    { "Ville": "Fès", "Région": "Ain Chkef" },
    { "Ville": "Fès", "Région": "Douiyet" },
    { "Ville": "Fès", "Région": "Sidi Brahim" },
    { "Ville": "Fès", "Région": "Ben Souda" },
    { "Ville": "Fès", "Région": "Hay Hassani" },
    { "Ville": "Tanger", "Région": "Tanger Al-Madina" },
    { "Ville": "Tanger", "Région": "Béni Makada" },
    { "Ville": "Tanger", "Région": "Souani" },
    { "Ville": "Tanger", "Région": "M'gougha" },
    { "Ville": "Tanger", "Région": "Marshan" },
    { "Ville": "Tanger", "Région": "Malabata" },
    { "Ville": "Tanger", "Région": "Mesnana" },
    { "Ville": "Tanger", "Région": "Val Fleuri" },
    { "Ville": "Tanger", "Région": "Iberia" },
    { "Ville": "Tanger", "Région": "California" },
    { "Ville": "Tanger", "Région": "Jbel Kbir" },
    { "Ville": "Tanger", "Région": "Gzenaya" },
    { "Ville": "Tanger", "Région": "Dradeb" },
    { "Ville": "Tanger", "Région": "Boukhalef" },
    { "Ville": "Tanger", "Région": "Branes" },
    { "Ville": "Tanger", "Région": "Casabarata" },
    { "Ville": "Tanger", "Région": "Achakkar" },
    { "Ville": "Tanger", "Région": "M'nar" },
    { "Ville": "Marrakech", "Région": "Guéliz" },
    { "Ville": "Marrakech", "Région": "Ménara" },
    { "Ville": "Marrakech", "Région": "Médina" },
    { "Ville": "Marrakech", "Région": "Sidi Youssef Ben Ali" },
    { "Ville": "Marrakech", "Région": "Annakhil (Palmeraie)" },
    { "Ville": "Marrakech", "Région": "Hivernage" },
    { "Ville": "Marrakech", "Région": "Daoudiate" },
    { "Ville": "Marrakech", "Région": "Massira I" },
    { "Ville": "Marrakech", "Région": "Massira II" },
    { "Ville": "Marrakech", "Région": "Massira III" },
    { "Ville": "Marrakech", "Région": "Targa" },
    { "Ville": "Marrakech", "Région": "Sidi Abbad" },
    { "Ville": "Marrakech", "Région": "Majorelle" },
    { "Ville": "Marrakech", "Région": "Amerchich" },
    { "Ville": "Marrakech", "Région": "Izdihar" },
    { "Ville": "Marrakech", "Région": "Bab Doukkala" },
    { "Ville": "Marrakech", "Région": "Kasbah" },
    { "Ville": "Marrakech", "Région": "Mellah" },
    { "Ville": "Marrakech", "Région": "Azzouzia" },
    { "Ville": "Marrakech", "Région": "M'hamid" },
    { "Ville": "Marrakech", "Région": "Sokoma" },
    { "Ville": "Salé", "Région": "Bab Lamrisa" },
    { "Ville": "Salé", "Région": "Haye Salam" },
    { "Ville": "Salé", "Région": "Tabriquet" },
    { "Ville": "Salé", "Région": "Bettana" },
    { "Ville": "Salé", "Région": "Layayda" },
    { "Ville": "Salé", "Région": "Hssaine" },
    { "Ville": "Salé", "Région": "Sidi Bouknadel" },
    { "Ville": "Salé", "Région": "Karia" },
    { "Ville": "Salé", "Région": "Said Hajji" },
    { "Ville": "Salé", "Région": "Moulay Ismail" },
    { "Ville": "Salé", "Région": "Rmel" },
    { "Ville": "Meknès", "Région": "Hamria" },
    { "Ville": "Meknès", "Région": "Bassatine" },
    { "Ville": "Meknès", "Région": "Mansour" },
    { "Ville": "Meknès", "Région": "Sidi Baba" },
    { "Ville": "Meknès", "Région": "Ville Nouvelle" },
    { "Ville": "Meknès", "Région": "Plata" },
    { "Ville": "Meknès", "Région": "Toulal" },
    { "Ville": "Meknès", "Région": "Ouislane" },
    { "Ville": "Meknès", "Région": "Sidi Said" },
    { "Ville": "Meknès", "Région": "Marjane" },
    { "Ville": "Meknès", "Région": "Riad" },
    { "Ville": "Meknès", "Région": "Anassi" },
    { "Ville": "Agadir", "Région": "Cité Suisse" },
    { "Ville": "Agadir", "Région": "Founti" },
    { "Ville": "Agadir", "Région": "Talborjt" },
    { "Ville": "Agadir", "Région": "Haut Founty" },
    { "Ville": "Agadir", "Région": "Dakhla" },
    { "Ville": "Agadir", "Région": "Bensergao" },
    { "Ville": "Agadir", "Région": "Anza" },
    { "Ville": "Agadir", "Région": "Hay Mohammadi" },
    { "Ville": "Agadir", "Région": "Amsernat" },
    { "Ville": "Agadir", "Région": "Ihchach" },
    { "Ville": "Agadir", "Région": "Taddart" },
    { "Ville": "Agadir", "Région": "Tilila" },
    { "Ville": "Agadir", "Région": "Adrar" },
    { "Ville": "Agadir", "Région": "Aourir" },
    { "Ville": "Agadir", "Région": "Tamraght" },
    { "Ville": "Agadir", "Région": "Taghazout" },
    { "Ville": "Oujda", "Région": "Lazaret" },
    { "Ville": "Oujda", "Région": "Sidi Yahya" },
    { "Ville": "Oujda", "Région": "Quartier Européen" },
    { "Ville": "Oujda", "Région": "Al Qods" },
    { "Ville": "Oujda", "Région": "Hay Anas" },
    { "Ville": "Oujda", "Région": "Sidi Maafa" },
    { "Ville": "Oujda", "Région": "Bni Drar" },
    { "Ville": "Kenitra", "Région": "Centre-ville" },
    { "Ville": "Kenitra", "Région": "Ville Haute" },
    { "Ville": "Kenitra", "Région": "Val Fleuri" },
    { "Ville": "Kenitra", "Région": "Mehdia" },
    { "Ville": "Kenitra", "Région": "Maamora" },
    { "Ville": "Kenitra", "Région": "Bir Rami" },
    { "Ville": "Kenitra", "Région": "Ouled Oujih" },
    { "Ville": "Kenitra", "Région": "Lafarge" },
    { "Ville": "Tétouan", "Région": "El Ensanche" },
    { "Ville": "Tétouan", "Région": "Médina" },
    { "Ville": "Tétouan", "Région": "M'hannech" },
    { "Ville": "Tétouan", "Région": "Touabel" },
    { "Ville": "Tétouan", "Région": "Kwilma" },
    { "Ville": "Tétouan", "Région": "Saniat Rmel" },
    { "Ville": "Tétouan", "Région": "Martil" },
    { "Ville": "Tétouan", "Région": "Cabo Negro" },
    { "Ville": "Tétouan", "Région": "M'diq" },
    { "Ville": "Tétouan", "Région": "Fnideq" },
    { "Ville": "Témara", "Région": "Harhoura" },
    { "Ville": "Témara", "Région": "Massira" },
    { "Ville": "Témara", "Région": "Wifaq" },
    { "Ville": "Témara", "Région": "Skhirat" },
    { "Ville": "Témara", "Région": "Ain Attig" },
    { "Ville": "Témara", "Région": "Mers El Kheir" },
    { "Ville": "Témara", "Région": "Haye Ennour" },
    { "Ville": "Essaouira", "Région": "Centre" },
    { "Ville": "Essaouira", "Région": "Médina" },
    { "Ville": "Essaouira", "Région": "Bab Doukkala" },
    { "Ville": "Essaouira", "Région": "Moulay Bouzerktoun" },
    { "Ville": "Essaouira", "Région": "Ghazoua" },
    { "Ville": "Safi", "Région": "Médina" },
    { "Ville": "Safi", "Région": "Plateau" },
    { "Ville": "Safi", "Région": "Kors" },
    { "Ville": "Safi", "Région": "Biyada" },
    { "Ville": "Safi", "Région": "Zaward" },
    { "Ville": "Safi", "Région": "Sania" },
    { "Ville": "Mohammedia", "Région": "Kasbah" },
    { "Ville": "Mohammedia", "Région": "Parc" },
    { "Ville": "Mohammedia", "Région": "Monaco" },
    { "Ville": "Mohammedia", "Région": "La Siesta" },
    { "Ville": "Mohammedia", "Région": "Les Sablettes" },
    { "Ville": "Mohammedia", "Région": "Haye El Falah" },
    { "Ville": "Mohammedia", "Région": "El Alia" },
    { "Ville": "Mohammedia", "Région": "Beni Yakhlef" },
    { "Ville": "Khouribga", "Région": "Centre" },
    { "Ville": "Khouribga", "Région": "Oued Zem" },
    { "Ville": "Khouribga", "Région": "Boujniba" },
    { "Ville": "Khouribga", "Région": "Haye Salam" },
    { "Ville": "Khouribga", "Région": "Bejaâd" },
    { "Ville": "Béni Mellal", "Région": "Kasbah" },
    { "Ville": "Béni Mellal", "Région": "Ain Asserdoun" },
    { "Ville": "Béni Mellal", "Région": "Ouled Hamdan" },
    { "Ville": "Béni Mellal", "Région": "Foum El Anceur" },
    { "Ville": "Nador", "Région": "Lamsalla" },
    { "Ville": "Nador", "Région": "Al Matar" },
    { "Ville": "Nador", "Région": "Beni Ensar" },
    { "Ville": "Nador", "Région": "Zeghanghane" },
    { "Ville": "Nador", "Région": "Selouane" },
    { "Ville": "Nador", "Région": "Kariat Arekmane" },
    { "Ville": "Settat", "Région": "Centre" },
    { "Ville": "Settat", "Région": "Miftah El Kheir" },
    { "Ville": "Settat", "Région": "Sidi Abdelkrim" },
    { "Ville": "Settat", "Région": "Oulad Said" },
    { "Ville": "Al Hoceima", "Région": "Centre" },
    { "Ville": "Al Hoceima", "Région": "Imzouren" },
    { "Ville": "Al Hoceima", "Région": "Bni Bouayach" },
    { "Ville": "Al Hoceima", "Région": "Ajdir" },
    { "Ville": "Al Hoceima", "Région": "Tala Youssef" },
    { "Ville": "Taourirt", "Région": "Centre" },
    { "Ville": "Taourirt", "Région": "Hay El Fath" },
    { "Ville": "Taourirt", "Région": "Hay Es-Salam" },
    { "Ville": "Taourirt", "Région": "El Aioun Sidi Mellouk" },
    { "Ville": "Berkane", "Région": "Centre" },
    { "Ville": "Berkane", "Région": "Saidïa" },
    { "Ville": "Berkane", "Région": "Ahfir" },
    { "Ville": "Berkane", "Région": "Hay Mohammadi" },
    { "Ville": "Berkane", "Région": "Sidi Slimane Echcharra" },
    { "Ville": "Laâyoune", "Région": "Centre" },
    { "Ville": "Laâyoune", "Région": "Colmina" },
    { "Ville": "Laâyoune", "Région": "Al Qassam" },
    { "Ville": "Laâyoune", "Région": "El Marsa" },
    { "Ville": "Laâyoune", "Région": "Boujdour (Ville proche)" },
    { "Ville": "Guelmim", "Région": "Centre" },
    { "Ville": "Guelmim", "Région": "Abainou" },
    { "Ville": "Guelmim", "Région": "Bouizakarne" },
    { "Ville": "Guelmim", "Région": "Sidi Ifni" },
    { "Ville": "El Jadida", "Région": "Plage" },
    { "Ville": "El Jadida", "Région": "Plateau" },
    { "Ville": "El Jadida", "Région": "Sidi Bouzid" },
    { "Ville": "El Jadida", "Région": "Moussa Ben Noussair" },
    { "Ville": "El Jadida", "Région": "Azemmour" },
    { "Ville": "Chefchaouen", "Région": "Médina" },
    { "Ville": "Chefchaouen", "Région": "Ras El Maa" },
    { "Ville": "Chefchaouen", "Région": "Sebanine" },
    { "Ville": "Chefchaouen", "Région": "Ville Nouvelle" },
    { "Ville": "Ouarzazate", "Région": "Centre" },
    { "Ville": "Ouarzazate", "Région": "Tabounte" },
    { "Ville": "Ouarzazate", "Région": "Tarmigte" },
    { "Ville": "Ouarzazate", "Région": "Kasbah Taourirt" },
    { "Ville": "Asilah", "Région": "Centre" },
    { "Ville": "Asilah", "Région": "Médina" },
    { "Ville": "Asilah", "Région": "Port" },
    { "Ville": "Ifrane", "Région": "Centre" },
    { "Ville": "Ifrane", "Région": "Azرو" },
    { "Ville": "Ifrane", "Région": "Michlifen" },
    { "Ville": "Tiznit", "Région": "Médina" },
    { "Ville": "Tiznit", "Région": "Id Ougfa" },
    { "Ville": "Tiznit", "Région": "Aït Mohammed" },
    { "Ville": "Tiznit", "Région": "Aglou" },
    { "Ville": "Larache", "Région": "Centre" },
    { "Ville": "Larache", "Région": "Hay El Maghreb El Arabi" },
    { "Ville": "Larache", "Région": "Hay Smara" },
    { "Ville": "Ksar El Kebir", "Région": "Centre" },
    { "Ville": "Ksar El Kebir", "Région": "Hay Châabane" },
    { "Ville": "Ksar El Kebir", "Région": "Hay Salam" },
    { "Ville": "Guercif", "Région": "Centre" },
    { "Ville": "Guercif", "Région": "Hay Es-Saada" },
    { "Ville": "Guercif", "Région": "Hay Al-Horria" },
    { "Ville": "Taounate", "Région": "Centre" },
    { "Ville": "Taounate", "Région": "Tissa" },
    { "Ville": "Taounate", "Région": "Ghessala" },
    { "Ville": "Sidi Kacem", "Région": "Centre" },
    { "Ville": "Sidi Kacem", "Région": "Mechra Bel Ksiri" },
    { "Ville": "Sidi Kacem", "Région": "Hay Zidani" },
    { "Ville": "Sidi Slimane", "Région": "Centre" },
    { "Ville": "Sidi Slimane", "Région": "Hay Es-Salam" },
    { "Ville": "Sidi Slimane", "Région": "Sidi Yahya El Gharb" },
    { "Ville": "Midelt", "Région": "Centre" },
    { "Ville": "Midelt", "Région": "Itzer" },
    { "Ville": "Boujdour", "Région": "Centre" },
    { "Ville": "Smara", "Région": "Centre" },
    { "Ville": "Tan-Tan", "Région": "Centre" },
    { "Ville": "Assa-Zag", "Région": "Centre" },
    { "Ville": "Tata", "Région": "Centre" },
    { "Ville": "Tinghir", "Région": "Centre" },
    { "Ville": "Tinghir", "Région": "Boumalne Dades" },
    { "Ville": "Zagora", "Région": "Centre" },
    { "Ville": "Zagora", "Région": "Agdz" },
    { "Ville": "Azilal", "Région": "Centre" },
    { "Ville": "Fquih Ben Salah", "Région": "Centre" },
    { "Ville": "Fquih Ben Salah", "Région": "Souk Sebt" },
    { "Ville": "Youssoufia", "Région": "Centre" },
    { "Ville": "Benguerir", "Région": "Centre" },
    { "Ville": "Kalaat Sraghna", "Région": "Centre" },
    { "Ville": "Sefrou", "Région": "Centre" },
    { "Ville": "Sefrou", "Région": "Bhalil" },
    { "Ville": "Berrechid", "Région": "Centre" },
    { "Ville": "Berrechid", "Région": "Had Soualem" },
    { "Ville": "Benslimane", "Région": "Centre" },
    { "Ville": "Benslimane", "Région": "Bouznika" },
    { "Ville": "Taroudant", "Région": "Centre" },
    { "Ville": "Taroudant", "Région": "Oulad Teïma" },
    { "Ville": "Khemisset", "Région": "Centre" },
    { "Ville": "Khemisset", "Région": "Tiflet" },
    { "Ville": "Taza", "Région": "Centre" },
    { "Ville": "Ouazzane", "Région": "Centre" },
    { "Ville": "Sidi Bennour", "Région": "Centre" },
    { "Ville": "Zhenghane", "Région": "Centre" },
    { "Ville": "Aïn Harrouda", "Région": "Centre" },
    { "Ville": "Skhirat", "Région": "Centre" },
    { "Ville": "Martil", "Région": "Centre" },
    { "Ville": "M'diq", "Région": "Centre" },
    { "Ville": "Fnideq", "Région": "Centre" }
];
